// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/31/2025, 6:06:58 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/user/Downloads/banking-app-nuxt3/banking-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/banking-app-nuxt3/banking-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/banking-app-nuxt3/banking-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/banking-app-nuxt3/banking-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/banking-app-nuxt3/banking-app/plugins/**/*.{js,ts,mjs}","C:/Users/user/Downloads/banking-app-nuxt3/banking-app/composables/**/*.{js,ts,mjs}","C:/Users/user/Downloads/banking-app-nuxt3/banking-app/utils/**/*.{js,ts,mjs}","C:/Users/user/Downloads/banking-app-nuxt3/banking-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/banking-app-nuxt3/banking-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/banking-app-nuxt3/banking-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/banking-app-nuxt3/banking-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;